service: gasbot-task

frameworkVersion: '2'
useDotenv: true

provider:
  name: aws
  region: us-west-2
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}

functions:
  rateHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(15 minutes)

plugins:
  - serverless-offline
